version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: todo-list-db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@todo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - todo-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge